### ISSUE TITLE
is:issue is:open 楼主你看：请问一下，我想用你的代码实现我自己的数据集训练，我的数据集是关于帕金森或者多系统萎缩的MRI和PET图像，做一个二分的任务。

### ISSUE THREAD

**Issue by Tanhongyun** [sagizty/MIL-SI#1]
is:issue is:open 楼主你看：请问一下，我想用你的代码实现我自己的数据集训练，我的数据集是关于帕金森或者多系统萎缩的MRI和PET图像，做一个二分的任务。

**Comment by sagizty** [comment]
您好，您需要吧您的数据处理成2D的，ImageFolder格式然后就可以使用这个框架训练。

**Comment by Tanhongyun** [comment]
知道了，但是代码是自己写的。



---原始邮件---
发件人: "Tianyi ***@***.***&gt;
发送时间: 2024年2月11日(周日) 下午2:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sagizty/MIL-SI] is:issue is:open 楼主你看：请问一下，我想用你的代码实现我自己的数据集训练，我的数据集是关于帕金森或者多系统萎缩的MRI和PET图像，做一个二分的任务。 (Issue #1)




 
您好，您需要吧您的数据处理成2D的，ImageFolder格式然后就可以使用这个框架训练。
